AUTHOR="skyldpod"
THEME="theme/basic"
SITEURL="https://skyldpod.github.io"
SITENAME="Turtle Blurg"
TIMEZONE='America/New_York'
ARTICLE_URL="posts/{slug}.html"
ARTICLE_SAVE_AS="posts/{slug}.html"
DISPLAY_CATEGORIES_ON_MENU=False
DEFAULT_CATEGORY='misc'
STATIC_PATHS=['images','extra']
EXTRA_PATH_METADATA={'extra/favicon.ico': {'path': 'favicon.ico'}}
PLUGIN_PATHS=['./render-math/pelican/plugins']
PLUGINS = ['render_math']
