name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: skyldpod/pelican-themes
        path: './theme'
    - uses: actions/checkout@v2
      with:
        repository: pelican-plugins/render-math
        path: './render-math'
    - uses: skyldpod/gh-pages-pelican-action@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_THEME_FOLDER: theme/basic
